import type { Challenge } from './types';

export const CHALLENGES: Challenge[] = [
  {
    id: 'ch-1',
    title: 'Tu primer ahorro',
    difficulty: 'Principiante',
    scenario: 'Recibes una mesada de $50.000 al mes. Tus gastos necesarios son $30.000.',
    question: '¿Cuánto deberías ahorrar como mínimo siguiendo la regla 50/30/20?',
    options: [
      { id: 'a', text: '$10.000 (20%)', correct: true, explanation: 'Correcto. La regla 50/30/20 destina el 20% al ahorro: $10.000.' },
      { id: 'b', text: '$5.000 (10%)', correct: false, explanation: 'No. La regla sugiere 20%, no 10%.' },
      { id: 'c', text: '$25.000 (50%)', correct: false, explanation: 'No. El 50% es para necesidades, no ahorro.' },
    ],
    points: 50,
    badge: 'first-challenge',
  },
  {
    id: 'ch-2',
    title: 'Necesidad o deseo',
    difficulty: 'Principiante',
    scenario: 'Estás en el centro comercial con $100.000 para el mes.',
    question: '¿Qué compra es claramente un deseo y no una necesidad?',
    options: [
      { id: 'a', text: 'Un mercado de alimentos', correct: false, explanation: 'No. La comida es una necesidad.' },
      { id: 'b', text: 'Unos audífonos de lujo', correct: true, explanation: 'Correcto. Los audífonos de lujo son un deseo, no una necesidad.' },
      { id: 'c', text: 'El pago del transporte', correct: false, explanation: 'No. Transportarse es una necesidad.' },
    ],
    points: 50,
  },
  {
    id: 'ch-3',
    title: 'El poder del interés compuesto',
    difficulty: 'Aprendiz',
    scenario: 'Tienes $1.000.000 y puedes invertir al 10% anual con interés compuesto durante 3 años.',
    question: '¿Cuál será el valor aproximado al final?',
    options: [
      { id: 'a', text: '$1.300.000 (interés simple)', correct: false, explanation: 'No. El compuesto da más que el simple.' },
      { id: 'b', text: '$1.331.000 (compuesto)', correct: true, explanation: 'Correcto. 1.000.000 × 1,1 × 1,1 × 1,1 ≈ 1.331.000.' },
      { id: 'c', text: '$1.100.000', correct: false, explanation: 'No. Eso sería un solo año.' },
    ],
    points: 80,
  },
  {
    id: 'ch-4',
    title: 'Inflación y ahorro',
    difficulty: 'Aprendiz',
    scenario: 'Guardas $1.000.000 bajo el colchón. La inflación anual es del 5%.',
    question: 'Después de un año, ¿cuánto vale realmente ese dinero?',
    options: [
      { id: 'a', text: '$1.050.000', correct: false, explanation: 'No. Guardado no genera interés.' },
      { id: 'b', text: '$950.000 en poder de compra', correct: true, explanation: 'Correcto. La inflación le quita valor: $1.000.000 × 0,95 ≈ $950.000.' },
      { id: 'c', text: 'Sigue valiendo $1.000.000', correct: false, explanation: 'No. El poder de compra baja con la inflación.' },
    ],
    points: 80,
  },
  {
    id: 'ch-5',
    title: 'Comparando tasas',
    difficulty: 'Aprendiz',
    scenario: 'Dos bancos te ofrecen un crédito de $500.000. Banco A: 18% anual. Banco B: 25% anual.',
    question: '¿Cuál conviene más y por qué?',
    options: [
      { id: 'a', text: 'Banco A, porque la tasa es menor', correct: true, explanation: 'Correcto. Menor tasa significa pagar menos interés.' },
      { id: 'b', text: 'Banco B, porque suena más grande', correct: false, explanation: 'No. Mayor tasa significa más costo, no más beneficio.' },
      { id: 'c', text: 'Da igual, las tasas no importan', correct: false, explanation: 'No. La tasa cambia mucho lo que pagas.' },
    ],
    points: 80,
  },
  {
    id: 'ch-6',
    title: 'Diversificación',
    difficulty: 'Estratega',
    scenario: 'Tienes $10.000.000 para invertir. Un amigo te dice que pongas todo en una sola acción que "seguro sube".',
    question: '¿Qué es lo más prudente?',
    options: [
      { id: 'a', text: 'Poner todo en esa acción', correct: false, explanation: 'No. Concentrar todo es muy riesgoso.' },
      { id: 'b', text: 'Repartir en varias inversiones distintas', correct: true, explanation: 'Correcto. Diversificar reduce el riesgo.' },
      { id: 'c', text: 'No invertir nada y guardarlo bajo el colchón', correct: false, explanation: 'No. La inflación le quitaría valor.' },
    ],
    points: 120,
  },
  {
    id: 'ch-7',
    title: 'Riesgo y rentabilidad',
    difficulty: 'Estratega',
    scenario: 'Una inversión promete 40% de rentabilidad anual garantizada.',
    question: '¿Qué deberías pensar?',
    options: [
      { id: 'a', text: 'Es una gran oportunidad, hay que aprovecharla', correct: false, explanation: 'No. Rentabilidad altísima "garantizada" suele ser engaño.' },
      { id: 'b', text: 'Desconfiar: alta rentabilidad implica alto riesgo o fraude', correct: true, explanation: 'Correcto. Si suena demasiado bueno, desconfía.' },
      { id: 'c', text: 'Que no hay ningún riesgo', correct: false, explanation: 'No. Toda inversión tiene riesgo.' },
    ],
    points: 120,
  },
  {
    id: 'ch-8',
    title: 'El dólar y tus compras',
    difficulty: 'Estratega',
    scenario: 'Quieres comprar un curso online que cuesta US$50. La tasa de cambio está en $4.000 COP.',
    question: '¿Cuánto pagarás en pesos colombianos?',
    options: [
      { id: 'a', text: '$200.000 COP', correct: true, explanation: 'Correcto. US$50 × $4.000 = $200.000 COP.' },
      { id: 'b', text: '$50.000 COP', correct: false, explanation: 'No. Debes multiplicar por la tasa de cambio.' },
      { id: 'c', text: '$4.050 COP', correct: false, explanation: 'No. La operación es 50 × 4.000.' },
    ],
    points: 120,
  },
  {
    id: 'ch-9',
    title: 'Oferta y demanda',
    difficulty: 'Maestro',
    scenario: 'Un celular nuevo sale al mercado. Mucha gente lo quiere, pero hay pocas unidades disponibles.',
    question: '¿Qué pasará con el precio?',
    options: [
      { id: 'a', text: 'Subirá, porque la demanda supera a la oferta', correct: true, explanation: 'Correcto. Mucha demanda con poca oferta eleva el precio.' },
      { id: 'b', text: 'Bajará, porque hay pocos productos', correct: false, explanation: 'No. La escasez con alta demanda sube el precio.' },
      { id: 'c', text: 'No cambiará', correct: false, explanation: 'No. El mercado ajusta el precio.' },
    ],
    points: 180,
  },
  {
    id: 'ch-10',
    title: 'Decisión de portafolio',
    difficulty: 'Maestro',
    scenario: 'Tienes un portafolio con todo el dinero en una sola acción. El mercado entra en crisis.',
    question: '¿Cuál es la mejor estrategia de largo plazo?',
    options: [
      { id: 'a', text: 'Vender todo en pánico', correct: false, explanation: 'No. Vender en pánico suele generar pérdidas grandes.' },
      { id: 'b', text: 'Mantener y diversificar poco a poco', correct: true, explanation: 'Correcto. Diversificar y pensar a largo plazo reduce riesgos.' },
      { id: 'c', text: 'Pedir un crédito para comprar más de esa acción', correct: false, explanation: 'No. Endeudarse para concentrar más es muy riesgoso.' },
    ],
    points: 180,
  },
];
