import type { Module } from './types';

export const MODULES: Module[] = [
  {
    id: 'basicos',
    title: 'Conceptos básicos de finanzas',
    emoji: '💡',
    description: 'Qué son las finanzas y por qué importan en tu día a día.',
    color: 'from-sky-400 to-blue-500',
    lessons: [
      {
        id: 'bas-1',
        title: '¿Qué son las finanzas?',
        emoji: '💡',
        intro: 'Las finanzas son la forma en que administramos el dinero: cuánto entra, cuánto sale y cómo lo usamos para lograr nuestros objetivos.',
        example: 'Piensa en tu mesada. Si recibes $20.000 y gastas $15.000, te sobran $5.000. ¡Eso ya es hacer finanzas!',
        question: 'Las finanzas se refieren principalmente a:',
        options: [
          { id: 'a', text: 'La administración del dinero', correct: true, explanation: 'Correcto. Las finanzas tratan de cómo gestionamos el dinero que entra y sale.' },
          { id: 'b', text: 'Solo invertir en la bolsa', correct: false, explanation: 'No solo. Invertir es una parte, pero las finanzas incluyen ahorrar, gastar y planear.' },
          { id: 'c', text: 'Trabajar en un banco', correct: false, explanation: 'No. Las finanzas las hacemos todos, no solo los bancos.' },
        ],
        tip: 'Todos hacemos finanzas, incluso sin darnos cuenta.',
        points: 30,
      },
      {
        id: 'bas-2',
        title: 'Necesidades vs deseos',
        emoji: '🛒',
        intro: 'Una necesidad es algo indispensable para vivir (comida, vivienda). Un deseo es algo que te gustaría tener, pero puedes vivir sin él.',
        example: 'Comer almuerzo es una necesidad. Comprar un helado de lujo es un deseo.',
        question: '¿Cuál de estos es una necesidad?',
        options: [
          { id: 'a', text: 'Unos tenis de marca nuevos', correct: false, explanation: 'Los tenis de marca son un deseo; puedes usar otros más económicos.' },
          { id: 'b', text: 'El transporte para ir a estudiar', correct: true, explanation: 'Correcto. Transportarse para estudiar es una necesidad.' },
          { id: 'c', text: 'Una suscripción de streaming', correct: false, explanation: 'Es un deseo; puedes vivir sin ella.' },
        ],
        tip: 'Distinguir necesidades de deseos te ayuda a gastar mejor.',
        points: 30,
      },
    ],
  },
  {
    id: 'ahorro',
    title: 'Ahorro y presupuesto',
    emoji: '🐷',
    description: 'Cómo guardar dinero y organizar tus gastos.',
    color: 'from-emerald-400 to-teal-500',
    lessons: [
      {
        id: 'aho-1',
        title: '¿Para qué ahorrar?',
        emoji: '🐷',
        intro: 'Ahorrar es guardar una parte de tu dinero para el futuro. Te ayuda a enfrentar imprevistos y cumplir metas.',
        example: 'Si ahorras $1.000 cada semana, en un año tendrás $52.000 para algo importante.',
        question: 'El ahorro te ayuda principalmente a:',
        options: [
          { id: 'a', text: 'Gastar todo lo que ganas', correct: false, explanation: 'No. Ahorrar es lo contrario a gastar todo.' },
          { id: 'b', text: 'Prepararte para imprevistos y metas', correct: true, explanation: 'Correcto. El ahorro es tu red de seguridad.' },
          { id: 'c', text: 'Evitar pagar cuentas', correct: false, explanation: 'No. Ahorrar no significa dejar de pagar lo que debes.' },
        ],
        tip: 'Una buena regla: ahorra antes de gastar, no lo que sobre al final.',
        points: 35,
      },
      {
        id: 'aho-2',
        title: 'El presupuesto',
        emoji: '📊',
        intro: 'Un presupuesto es un plan que dice cómo vas a usar tu dinero. Lista tus ingresos y tus gastos.',
        example: 'Si recibes $50.000 y gastas $30.000 en necesidades, te quedan $20.000 para ahorrar o deseos.',
        question: '¿Qué hace un presupuesto?',
        options: [
          { id: 'a', text: 'Te ayuda a planear cómo usar tu dinero', correct: true, explanation: 'Correcto. Es un mapa de tus ingresos y gastos.' },
          { id: 'b', text: 'Te obliga a no gastar nada', correct: false, explanation: 'No. Un presupuesto organiza, no prohíbe gastar.' },
          { id: 'c', text: 'Solo sirve para empresas', correct: false, explanation: 'No. Cualquier persona puede hacer un presupuesto.' },
        ],
        tip: 'La regla 50/30/20: 50% necesidades, 30% deseos, 20% ahorro.',
        points: 35,
      },
    ],
  },
  {
    id: 'ingresos',
    title: 'Ingresos y gastos',
    emoji: '💰',
    description: 'El dinero que entra y el que sale de tu bolsillo.',
    color: 'from-amber-400 to-orange-500',
    lessons: [
      {
        id: 'ing-1',
        title: 'Ingresos',
        emoji: '💰',
        intro: 'Los ingresos son todo el dinero que recibes: mesada, salario, regalos o ventas.',
        example: 'Si vendes limonada y ganas $5.000, eso es un ingreso.',
        question: 'Un ingreso es:',
        options: [
          { id: 'a', text: 'Dinero que recibes', correct: true, explanation: 'Correcto. Todo dinero que entra es un ingreso.' },
          { id: 'b', text: 'Dinero que gastas', correct: false, explanation: 'No. Eso es un gasto.' },
          { id: 'c', text: 'Dinero que pides prestado', correct: false, explanation: 'Pedir prestado no es un ingreso, es una deuda.' },
        ],
        tip: 'Conocer tus ingresos te permite planear tus gastos.',
        points: 30,
      },
      {
        id: 'ing-2',
        title: 'Gastos',
        emoji: '💸',
        intro: 'Los gastos son el dinero que sale. Pueden ser fijos (siempre los pagas) o variables (cambian cada mes).',
        example: 'El recibo de luz es un gasto fijo. Salir al cine es un gasto variable.',
        question: 'Un gasto fijo es aquel que:',
        options: [
          { id: 'a', text: 'Cambia cada mes sin razón', correct: false, explanation: 'No. Los gastos fijos son estables.' },
          { id: 'b', text: 'Pagas de forma constante cada mes', correct: true, explanation: 'Correcto. Como el arriendo o un servicio mensual.' },
          { id: 'c', text: 'Solo pagas una vez al año', correct: false, explanation: 'No. Los fijos se repiten con regularidad.' },
        ],
        tip: 'Reduce gastos hormiga (café, snacks) para ahorrar más sin notarlo.',
        points: 30,
      },
    ],
  },
  {
    id: 'interes',
    title: 'Interés simple y compuesto',
    emoji: '📈',
    description: 'Cómo crece el dinero con el tiempo.',
    color: 'from-blue-500 to-indigo-500',
    lessons: [
      {
        id: 'int-1',
        title: 'Interés simple',
        emoji: '➗',
        intro: 'El interés simple es una ganancia que se calcula solo sobre el dinero inicial, siempre igual.',
        example: 'Si prestas $1.000 al 10% anual, cada año ganas $100, siempre lo mismo.',
        question: 'En el interés simple, la ganancia cada año es:',
        options: [
          { id: 'a', text: 'Cada vez mayor', correct: false, explanation: 'No. En el interés simple no crece.' },
          { id: 'b', text: 'Igual todos los años', correct: true, explanation: 'Correcto. Siempre se calcula sobre el dinero inicial.' },
          { id: 'c', text: 'Cada vez menor', correct: false, explanation: 'No. Se mantiene constante.' },
        ],
        tip: 'Interés simple = dinero inicial × tasa × tiempo.',
        points: 40,
      },
      {
        id: 'int-2',
        title: 'Interés compuesto',
        emoji: '✨',
        intro: 'El interés compuesto es "interés sobre interés". Las ganancias se reinvierten y el dinero crece más rápido.',
        example: 'Si inviertes $1.000 al 10% compuesto, el segundo año ganas $110, no $100, porque ganas interés sobre $1.100.',
        question: 'El interés compuesto hace que el dinero crezca:',
        options: [
          { id: 'a', text: 'Más rápido que el simple', correct: true, explanation: 'Correcto. Porque ganas interés sobre los intereses.' },
          { id: 'b', text: 'Igual que el simple', correct: false, explanation: 'No. El compuesto crece más con el tiempo.' },
          { id: 'c', text: 'Más lento que el simple', correct: false, explanation: 'No. Es al revés.' },
        ],
        tip: 'Albert Einstein llamó al interés compuesto "la octava maravilla del mundo".',
        points: 40,
      },
    ],
  },
  {
    id: 'inflacion',
    title: 'Inflación',
    emoji: '🔥',
    description: 'Por qué las cosas cuestan más con el tiempo.',
    color: 'from-rose-400 to-red-500',
    lessons: [
      {
        id: 'inf-1',
        title: '¿Qué es la inflación?',
        emoji: '🔥',
        intro: 'La inflación es el aumento general de los precios con el tiempo. Con el mismo dinero, puedes comprar menos.',
        example: 'Si un pan costaba $500 hace un año y hoy cuesta $550, hubo inflación.',
        question: 'La inflación significa que:',
        options: [
          { id: 'a', text: 'El dinero pierde poder de compra', correct: true, explanation: 'Correcto. Con el mismo dinero compras menos.' },
          { id: 'b', text: 'Las cosas son más baratas', correct: false, explanation: 'No. La inflación sube los precios.' },
          { id: 'c', text: 'Ganas más salario automáticamente', correct: false, explanation: 'No. El salario no siempre sube con la inflación.' },
        ],
        tip: 'Por eso no es bueno guardar todo tu dinero bajo el colchón: pierde valor.',
        points: 35,
      },
    ],
  },
  {
    id: 'credito',
    title: 'Crédito, préstamos y tasas',
    emoji: '🏦',
    description: 'Pedir dinero prestado con responsabilidad.',
    color: 'from-cyan-400 to-blue-500',
    lessons: [
      {
        id: 'cre-1',
        title: '¿Qué es un crédito?',
        emoji: '🏦',
        intro: 'Un crédito es dinero que te prestan y debes devolver después, generalmente con un extra llamado interés.',
        example: 'Pides prestado $10.000 y devuelves $11.000. Ese $1.000 extra es el interés.',
        question: 'Cuando pides un crédito, debes devolver:',
        options: [
          { id: 'a', text: 'Solo el dinero que pediste', correct: false, explanation: 'No. Generalmente también pagas interés.' },
          { id: 'b', text: 'El dinero prestado más interés', correct: true, explanation: 'Correcto. El interés es el costo del préstamo.' },
          { id: 'c', text: 'Más de lo que pediste, sin interés', correct: false, explanation: 'No. El extra es justamente el interés.' },
        ],
        tip: 'Compara tasas antes de pedir un crédito. Una tasa menor te ahorra mucho.',
        points: 35,
      },
      {
        id: 'cre-2',
        title: 'La tasa de interés',
        emoji: '🏷️',
        intro: 'La tasa de interés es el porcentaje extra que pagas por un préstamo o ganas por una inversión.',
        example: 'Una tasa del 20% sobre $1.000 significa pagar $200 extra al año.',
        question: 'Una tasa de interés más alta en un préstamo significa:',
        options: [
          { id: 'a', text: 'Pagas más dinero extra', correct: true, explanation: 'Correcto. Mayor tasa, mayor costo.' },
          { id: 'b', text: 'Pagas menos dinero extra', correct: false, explanation: 'No. Es al revés.' },
          { id: 'c', text: 'No pagas nada extra', correct: false, explanation: 'No. La tasa siempre genera un costo.' },
        ],
        tip: 'En Colombia, la usura es el límite legal que un cobrador puede cobrar.',
        points: 35,
      },
    ],
  },
  {
    id: 'riesgo',
    title: 'Riesgo y rentabilidad',
    emoji: '⚖️',
    description: 'La regla de oro: más ganancia posible, más riesgo.',
    color: 'from-violet-400 to-purple-500',
    lessons: [
      {
        id: 'rie-1',
        title: 'Riesgo vs rentabilidad',
        emoji: '⚖️',
        intro: 'Rentabilidad es la ganancia de una inversión. Riesgo es la posibilidad de perder dinero. A mayor rentabilidad, mayor riesgo.',
        example: 'Ahorrar en el colchón no tiene riesgo, pero no gana nada. Invertir en acciones puede ganar mucho, pero también perder.',
        question: 'Si una inversión ofrece mucha rentabilidad, generalmente:',
        options: [
          { id: 'a', text: 'Tiene poco riesgo', correct: false, explanation: 'No. Alta rentabilidad suele implicar más riesgo.' },
          { id: 'b', text: 'Tiene mayor riesgo', correct: true, explanation: 'Correcto. La regla es: a mayor ganancia posible, mayor riesgo.' },
          { id: 'c', text: 'No tiene riesgo', correct: false, explanation: 'No. Toda inversión tiene algún riesgo.' },
        ],
        tip: 'Nunca inviertas dinero que no puedas permitirte perder.',
        points: 40,
      },
    ],
  },
  {
    id: 'acciones',
    title: 'Acciones y bolsa',
    emoji: '🏛️',
    description: 'Qué significa ser dueño de una parte de una empresa.',
    color: 'from-blue-500 to-cyan-500',
    lessons: [
      {
        id: 'acc-1',
        title: '¿Qué es una acción?',
        emoji: '🏛️',
        intro: 'Una acción es un pedacito de una empresa. Si compras una acción, eres dueño de una pequeña parte de esa empresa.',
        example: 'Si una empresa vale $1.000.000 y tiene 1.000 acciones, cada acción vale $1.000.',
        question: 'Comprar una acción te convierte en:',
        options: [
          { id: 'a', text: 'Dueño de una parte de la empresa', correct: true, explanation: 'Correcto. Eres socio de la empresa.' },
          { id: 'b', text: 'Empleado de la empresa', correct: false, explanation: 'No. Tener acciones no te hace empleado.' },
          { id: 'c', text: 'Acreedor de la empresa', correct: false, explanation: 'No. Eres dueño, no prestamista.' },
        ],
        tip: 'El precio de una acción sube o baja según cómo va la empresa y el mercado.',
        points: 40,
      },
      {
        id: 'acc-2',
        title: 'La bolsa de valores',
        emoji: '📊',
        intro: 'La bolsa es el mercado donde se compran y venden acciones. En Colombia se llama BVC (Bolsa de Valores de Colombia).',
        example: 'Es como un mercado de frutas, pero en lugar de frutas se venden partes de empresas.',
        question: 'La bolsa es el lugar donde:',
        options: [
          { id: 'a', text: 'Se compran y venden acciones', correct: true, explanation: 'Correcto. Es el mercado de acciones.' },
          { id: 'b', text: 'Se guardan las acciones', correct: false, explanation: 'No. La bolsa es para transar, no para guardar.' },
          { id: 'c', text: 'Se fabrican las acciones', correct: false, explanation: 'No. Las acciones las emiten las empresas.' },
        ],
        tip: 'El índice COLCAP muestra el comportamiento de las principales empresas de Colombia.',
        points: 40,
      },
    ],
  },
  {
    id: 'fondos',
    title: 'Fondos de inversión',
    emoji: '🧺',
    description: 'Invertir junto a otros con ayuda de expertos.',
    color: 'from-teal-400 to-emerald-500',
    lessons: [
      {
        id: 'fon-1',
        title: '¿Qué es un fondo de inversión?',
        emoji: '🧺',
        intro: 'Un fondo junta el dinero de muchas personas y un experto lo invierte. Tú participas con poco dinero.',
        example: 'Como una vaca colectiva: muchos aportan y un experto decide qué comprar para todos.',
        question: 'Un fondo de inversión te permite:',
        options: [
          { id: 'a', text: 'Invertir con ayuda de expertos', correct: true, explanation: 'Correcto. Un profesional administra el fondo.' },
          { id: 'b', text: 'Evitar todo riesgo', correct: false, explanation: 'No. Los fondos también tienen riesgo.' },
          { id: 'c', text: 'No pagar comisiones', correct: false, explanation: 'No. Los fondos cobran una comisión por administrar.' },
        ],
        tip: 'Los fondos son una buena opción para empezar con poca experiencia.',
        points: 40,
      },
    ],
  },
  {
    id: 'diversificacion',
    title: 'Diversificación',
    emoji: '🥗',
    description: 'No poner todos los huevos en la misma canasta.',
    color: 'from-lime-400 to-green-500',
    lessons: [
      {
        id: 'div-1',
        title: '¿Qué es diversificar?',
        emoji: '🥗',
        intro: 'Diversificar es repartir tu dinero en varias inversiones para no depender de una sola.',
        example: 'Si inviertes todo en una empresa y le va mal, pierdes todo. Si repartes en cinco, el riesgo baja.',
        question: 'Diversificar significa:',
        options: [
          { id: 'a', text: 'Poner todo el dinero en una sola inversión', correct: false, explanation: 'No. Eso es lo contrario a diversificar.' },
          { id: 'b', text: 'Repartir el dinero en varias inversiones', correct: true, explanation: 'Correcto. Así reduces el riesgo.' },
          { id: 'c', text: 'No invertir nunca', correct: false, explanation: 'No. Diversificar es invertir de forma repartida.' },
        ],
        tip: 'La regla de oro: no pongas todos los huevos en la misma canasta.',
        points: 40,
      },
    ],
  },
  {
    id: 'monedas',
    title: 'Dólar y otras monedas',
    emoji: '💵',
    description: 'Cómo se comparan las monedas del mundo.',
    color: 'from-green-400 to-emerald-500',
    lessons: [
      {
        id: 'mon-1',
        title: 'El dólar y la tasa de cambio',
        emoji: '💵',
        intro: 'El dólar es la moneda de Estados Unidos. La tasa de cambio dice cuántos pesos colombianos necesitas para comprar un dólar.',
        example: 'Si la tasa es $4.000, necesitas $4.000 COP para comprar US$1.',
        question: 'Si el dólar sube frente al peso, comprar productos en dólares cuesta:',
        options: [
          { id: 'a', text: 'Más pesos', correct: true, explanation: 'Correcto. Un dólar más caro te cuesta más pesos.' },
          { id: 'b', text: 'Menos pesos', correct: false, explanation: 'No. Sube el costo en pesos.' },
          { id: 'c', text: 'Igual en pesos', correct: false, explanation: 'No. La tasa de cambio afecta el precio.' },
        ],
        tip: 'En Colombia seguimos mucho el dólar porque importamos y exportamos productos.',
        points: 35,
      },
    ],
  },
  {
    id: 'economia',
    title: 'Conceptos básicos de economía',
    emoji: '🌍',
    description: 'Cómo funciona el mundo del dinero.',
    color: 'from-indigo-400 to-blue-500',
    lessons: [
      {
        id: 'eco-1',
        title: 'Oferta y demanda',
        emoji: '🌍',
        intro: 'La oferta es cuánto hay de un producto. La demanda es cuánto lo quieren. Si mucha gente quiere algo y hay poco, sube el precio.',
        example: 'Si hay pocos tenis de un modelo exclusivo y muchos los quieren, el precio sube.',
        question: 'Si la demanda sube y la oferta se mantiene, el precio tiende a:',
        options: [
          { id: 'a', text: 'Subir', correct: true, explanation: 'Correcto. Más interés con igual cantidad sube el precio.' },
          { id: 'b', text: 'Bajar', correct: false, explanation: 'No. Más demanda con misma oferta sube el precio.' },
          { id: 'c', text: 'No cambiar', correct: false, explanation: 'No. El precio se ajusta.' },
        ],
        tip: 'La oferta y demanda explican casi todos los precios que ves.',
        points: 40,
      },
      {
        id: 'eco-2',
        title: 'El PIB',
        emoji: '📈',
        intro: 'El PIB (Producto Interno Bruto) es el valor total de lo que produce un país en un periodo. Mide el tamaño de su economía.',
        example: 'Si el PIB sube, el país está produciendo más. Si baja, la economía se contrae.',
        question: 'El PIB mide:',
        options: [
          { id: 'a', text: 'La producción total de un país', correct: true, explanation: 'Correcto. Es el valor de bienes y servicios producidos.' },
          { id: 'b', text: 'La cantidad de personas', correct: false, explanation: 'No. Eso es la población.' },
          { id: 'c', text: 'El precio del dólar', correct: false, explanation: 'No. El PIB no mide la tasa de cambio.' },
        ],
        tip: 'Cuando el PIB crece dos trimestres seguidos hacia abajo, se habla de recesión.',
        points: 40,
      },
    ],
  },
];
